name: carnegie-app
channels:
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - anyio=4.12.1=pyhcf101f3_0
  - anywidget=0.9.21=pyhd8ed1ab_0
  - appdirs=1.4.4=pyhd8ed1ab_1
  - asgiref=3.11.0=pyhcf101f3_1
  - asttokens=3.0.1=pyhd8ed1ab_0
  - backports.zstd=1.3.0=py312h06d0912_0
  - blas=1.0=mkl
  - blinker=1.9.0=pyhff2d567_0
  - brotli-python=1.2.0=py312hc6d9e41_1
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2026.1.4=h4c7d964_0
  - cachelib=0.13.0=pyhd8ed1ab_1
  - certifi=2026.1.4=pyhd8ed1ab_0
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - click=8.3.1=pyha7b4d00_1
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.3=pyhe01879c_0
  - dash=4.0.0=pyhd8ed1ab_0
  - dash-bootstrap-components=2.0.4=pyhcf101f3_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - et_xmlfile=2.0.0=pyhd8ed1ab_1
  - exceptiongroup=1.3.1=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - expat=2.7.4=hd7fb8db_0
  - flask=3.1.2=pyhd8ed1ab_0
  - flask-caching=2.3.1=pyhd8ed1ab_0
  - h11=0.16.0=pyhcf101f3_1
  - h2=4.3.0=pyhcf101f3_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - htmltools=0.6.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - idna=3.11=pyhd8ed1ab_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - intel-openmp=2025.0.0=haa95532_1164
  - ipython=9.10.0=pyhe2676ad_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - ipywidgets=8.1.8=pyhd8ed1ab_0
  - itsdangerous=2.2.0=pyhd8ed1ab_1
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhcf101f3_1
  - jupyter_core=5.9.1=pyh6dadd2b_0
  - jupyterlab_widgets=3.0.16=pyhcf101f3_1
  - libexpat=2.7.4=hd7fb8db_0
  - libffi=3.4.4=hd77b12b_1
  - libhwloc=2.12.1=default_hfa10c62_1000
  - libiconv=1.16=h2bbff1b_3
  - libxml2=2.13.9=h6201b9f_0
  - libzlib=1.3.1=h02ab6af_0
  - linkify-it-py=2.0.3=pyhd8ed1ab_1
  - markdown-it-py=4.0.0=pyhd8ed1ab_0
  - markupsafe=3.0.3=py312h05f76fc_0
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - mdit-py-plugins=0.5.0=pyhd8ed1ab_0
  - mdurl=0.1.2=pyhd8ed1ab_1
  - mkl=2025.0.0=h5da7b33_930
  - mkl-service=2.5.2=py312h0b37514_0
  - mkl_fft=2.1.1=py312h300f80d_0
  - mkl_random=1.3.0=py312ha5e6156_0
  - narwhals=2.16.0=pyhcf101f3_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - numpy=2.4.1=py312h050da96_0
  - numpy-base=2.4.1=py312h1e017a8_0
  - openpyxl=3.1.5=py312h83acffa_3
  - openssl=3.6.1=hf411b9b_1
  - orjson=3.11.5=py312hfb36fc7_0
  - packaging=25.0=py312haa95532_1
  - parso=0.8.5=pyhcf101f3_0
  - pip=25.3=pyhc872135_0
  - platformdirs=4.5.1=pyhcf101f3_0
  - plotly=6.5.2=pyhd8ed1ab_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - prompt_toolkit=3.0.52=hd8ed1ab_0
  - psygnal=0.15.0=pyhd8ed1ab_0
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - pysocks=1.7.1=pyh09c184e_7
  - python=3.12.7=h14ffc60_0
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-multipart=0.0.22=pyhcf101f3_0
  - python_abi=3.12=3_cp312
  - pywin32=311=py312h829343e_1
  - questionary=2.1.1=pyhd8ed1ab_0
  - requests=2.32.5=pyhcf101f3_1
  - retrying=1.4.2=pyhe01879c_0
  - setuptools=80.10.2=py312haa95532_0
  - shiny=1.4.0=pyhd8ed1ab_0
  - shinywidgets=0.7.1=pyhd8ed1ab_0
  - six=1.17.0=pyhe01879c_1
  - sqlite=3.51.1=hda9a48d_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - starlette=0.52.1=pyhfdc7a7d_0
  - tbb=2022.3.0=h90c84d6_0
  - tbb-devel=2022.3.0=h90c84d6_0
  - tk=8.6.15=hf199647_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing-extensions=4.15.0=h396c80c_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025c=he532380_0
  - uc-micro-py=1.0.3=pyhd8ed1ab_1
  - ucrt=10.0.22621.0=haa95532_0
  - urllib3=2.6.3=pyhd8ed1ab_0
  - uvicorn=0.40.0=pyh6dadd2b_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - watchfiles=1.1.1=py312hb0142fd_0
  - wcwidth=0.5.3=pyhd8ed1ab_0
  - websockets=16.0=py312he5662c2_1
  - werkzeug=3.1.5=pyhcf101f3_0
  - wheel=0.46.3=py312haa95532_0
  - widgetsnbextension=4.0.15=pyhd8ed1ab_0
  - win_inet_pton=1.1.0=pyh7428d3b_8
  - wrapt=2.1.1=py312he06e257_0
  - xz=5.6.4=h4754444_1
  - zipp=3.23.0=pyhcf101f3_1
  - zlib=1.3.1=h02ab6af_0
  - zstd=1.5.7=h534d264_6
prefix: C:\Users\marki\anaconda3\envs\carnegie-app
