name: carnegie-app
channels:
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - anyio=4.12.1=pyhcf101f3_0
  - appdirs=1.4.4=pyhd8ed1ab_1
  - asgiref=3.11.0=pyhcf101f3_1
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2026.1.4=h4c7d964_0
  - click=8.3.1=pyha7b4d00_1
  - colorama=0.4.6=pyhd8ed1ab_1
  - exceptiongroup=1.3.1=pyhd8ed1ab_0
  - expat=2.7.4=hd7fb8db_0
  - h11=0.16.0=pyhcf101f3_1
  - htmltools=0.6.0=pyhd8ed1ab_0
  - idna=3.11=pyhd8ed1ab_0
  - libexpat=2.7.4=hd7fb8db_0
  - libffi=3.4.4=hd77b12b_1
  - libzlib=1.3.1=h02ab6af_0
  - linkify-it-py=2.0.3=pyhd8ed1ab_1
  - markdown-it-py=4.0.0=pyhd8ed1ab_0
  - mdit-py-plugins=0.5.0=pyhd8ed1ab_0
  - mdurl=0.1.2=pyhd8ed1ab_1
  - narwhals=2.16.0=pyhcf101f3_0
  - openssl=3.6.1=hf411b9b_1
  - orjson=3.11.5=py312hfb36fc7_0
  - packaging=25.0=py312haa95532_1
  - pip=25.3=pyhc872135_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - prompt_toolkit=3.0.52=hd8ed1ab_0
  - python=3.12.7=h14ffc60_0
  - python-multipart=0.0.22=pyhcf101f3_0
  - python_abi=3.12=3_cp312
  - questionary=2.1.1=pyhd8ed1ab_0
  - setuptools=80.10.2=py312haa95532_0
  - shiny=1.4.0=pyhd8ed1ab_0
  - sqlite=3.51.1=hda9a48d_0
  - starlette=0.52.1=pyhfdc7a7d_0
  - tk=8.6.15=hf199647_0
  - typing-extensions=4.15.0=h396c80c_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025c=he532380_0
  - uc-micro-py=1.0.3=pyhd8ed1ab_1
  - ucrt=10.0.22621.0=haa95532_0
  - uvicorn=0.40.0=pyh6dadd2b_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - watchfiles=1.1.1=py312hb0142fd_0
  - wcwidth=0.5.3=pyhd8ed1ab_0
  - websockets=16.0=py312he5662c2_1
  - wheel=0.46.3=py312haa95532_0
  - xz=5.6.4=h4754444_1
  - zlib=1.3.1=h02ab6af_0
prefix: C:\Users\marki\anaconda3\envs\carnegie-app
